### ISSUE TITLE
Add ext/cassandra storage

### ISSUE THREAD

**Issue by beberlei** [doctrine/KeyValueStore#38]
Datastax released a Cassandra PHP Driver that we should support:

http://datastax.github.io/php-driver/

There is already a PR with experimental support in #24, but it was for a very early version of the driver.

**Comment by SenseException** [comment]
Does this need to be reviewed again with a newer version of the driver?

**Comment by EmanueleMinotto** [comment]
@SenseException that PR was for a pre-release, since it was started (7 months ago) the DataStax PHP driver reached a [v1.0 release](https://github.com/datastax/php-driver/releases/tag/v1.0.0) with many bugs fixed, I prefer to use it instead of a pre-release.
