### ISSUE TITLE
Add Amazon DynamoDB storage

### ISSUE THREAD

**Issue by beberlei** [doctrine/KeyValueStore#41]
Using the AWS SDK for PHP: http://docs.aws.amazon.com/aws-sdk-php/v3/api/namespace-Aws.DynamoDb.html

**Comment by larowlan** [comment]
Is this still open? https://github.com/doctrine/KeyValueStore/blob/master/lib/Doctrine/KeyValueStore/Storage/DynamoDbStorage.php seems to indicate there is a storage class, but #49 is still open? If so I'm interested in working on it.

**Comment by larowlan** [comment]
Discussed this with @EmanueleMinotto on irc and agreed that it makes sense to merge the best bits of this PR with the existing implementation added in https://github.com/stanlemon/KeyValueStore/pull/2 and add some recursive removal of empty attributes at the same time.
