### ISSUE TITLE
Update configuration.rst docs with all storages

### ISSUE THREAD

**Issue by beberlei** [doctrine/KeyValueStore#42]
The `docs/reference/configuration.rst` needs more support for all storages.

- [ ] Amazon DynamoDB  (see: https://github.com/doctrine/KeyValueStore/pull/49)
- [x] CouchDB (see: https://github.com/doctrine/KeyValueStore/pull/47)
- [x] Cassandra (see: https://github.com/doctrine/KeyValueStore/pull/24)

**Comment by EmanueleMinotto** [comment]
Still missing:
- [ ] Amazon DynamoDB  (see: https://github.com/doctrine/KeyValueStore/pull/49)
- [ ] CouchDB (see: https://github.com/doctrine/KeyValueStore/pull/47)
- [ ] Cassandra

**Comment by larowlan** [comment]
Will tackle this with #41

**Comment by larowlan** [comment]
https://github.com/nicktacular/KeyValueStore/pull/2 includes this, pending merge from @nicktacular will end up in #49
